name: Submit latest iOS build to App Store Connect

on:
  workflow_dispatch: {}

defaults:
  tools:
    node: 22.11.0
    yarn: '1.22.22'

jobs:
  get_ios_build:
    name: Get latest production iOS build
    type: get-build
    params:
      platform: ios
      profile: production
      distribution: store
      channel: production

  submit_ios:
    name: Submit iOS build to App Store Connect
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    env:
      EXPO_DEBUG: "1"
    type: submit
    params:
      build_id: ${{ needs.get_ios_build.outputs.build_id }}
      profile: production
